### ISSUE TITLE
Ajouter licence CC BY-SA

### ISSUE THREAD

**Issue by florimondmanca** [fairnesscoop/documentation#1]
Est-ce qu'on devrait ajouter une licence à ce repo ?

[Creative Commons BY-NC-SA](https://creativecommons.org/licenses/by-nc-sa/4.0/) ?

[Creative Commons BY-SA](https://creativecommons.org/licenses/by-sa/4.0/) ?

Ou aucune ? Par défaut le droit d'auteur s'applique.

**Comment by Volubyl** [comment]
Je pense que la [Create Comons BY-SA](https://creativecommons.org/licenses/by-sa/4.0/) serait p-e plus à propos.

Si je capte la différence c'est la notion de "utilisation commerciale"

Ma logique est que l'idée de ce wiki est fortement inspirée du wiki de beta.gouv.fr et que l'on est une entreprise commerciale.

Je trouverai ça donc un peu hypocrite d'interdire l'utilisation commerciale de ce wiki

**Comment by florimondmanca** [comment]
Je suis d'accord

**Comment by Volubyl** [comment]
Done :tada:

**Comment by florimondmanca** [comment]
Nice
